cluster:
  name: ${CLUSTER_NAME}
node:
  name: ${ELASTICSEARCH_NODE_NAME}
  master: true
  data: true
path:
  data: /usr/share/elasticsearch/es-data
  logs: /usr/share/elasticsearch/es-log
  plugins: /usr/share/elasticsearch/plugins
  work: /usr/share/elasticsearch/es-work
network:
  host: ${NETWORK_BIND_HOST}
discovery:
  type: ec2
  zen:
    ping:
      multicast:
        enabled: false
  ec2:
    tag:
      name: ${EC2_NODE_NAME}        
cloud:
  node:
    auto_attributes: true
  aws:
    region: eu-west-1
    s3: ${ES_S3_BUCKET_NAME}
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_KEY}
index:
  number_of_shards: 2
  number_of_replicas: 1
bootstrap:
  mlockall: true