path:
  data: /usr/share/elasticsearch/es-data
  logs: /usr/share/elasticsearch/es-log
  plugins: /usr/share/elasticsearch/plugins
  work: /usr/share/elasticsearch/es-work
network:
  host: 0.0.0.0
discovery:
  zen:
    ping:
      multicast:
        enabled: true
cluster:
  name: ${CLUSTER_NAME}